#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import os

agent.add_public_service(os.environ['MODULE_ID'], [
    "3478/tcp",
    "3478/udp",
    "50000-50500/udp",
])

# Ignore exit code
